services:
  web:
    container_name: meerkat-web
    build:
      context: ./src
      dockerfile: ../docker/Dockerfile
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    env_file:
      - docker/.env
    depends_on:
      - db
      - redis

  db:
    container_name: meerkat-db
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - docker/.env

  redis:
    container_name: meerkat-redis
    image: redis:7-alpine

volumes:
  postgres_data:
